executable              = run_deepjetcore3_lxplus_local.sh
arguments               = $(ClusterId)$(ProcId)
output                  = out/sing.$(ClusterId).$(ProcId).out
error                   = out/sing.$(ClusterId).$(ProcId).err
log                     = out/sing.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 1
+JobFlavour = "tomorrow"
+SingularityImage = "/eos/home-j/jkiesele/singularity/images/deepjetcore3_latest.sif"
queue
