executable              = $ENV(BTVHLTToolsDirectory)/submit/job_training.sh
arguments               = $(ClusterId)$(ProcId)
output                  = $ENV(TrainingOutput)/sing.$(ClusterId).$(ProcId).out
error                   = $ENV(TrainingOutput)/sing.$(ClusterId).$(ProcId).err
log                     = $ENV(TrainingOutput)/sing.$(ClusterId).log
should_transfer_files   = YES
getenv = True
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 1
+RequestRuntime = 172800
queue
